routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('principal');
});
Route::resource('pais','PaisController');
Route::resource('empresa','EmpresaController');
Route::resource('sucursal','SucursalController');
Route::resource('condicion','CondicionController');
Route::resource('moneda','MonedaController');
Route::resource('contenedor','ContenedorController');  
Route::resource('destino','DestinoController');
Route::resource('emision','EmisionController');
Route::resource('ciudad','CiudadController');
Route::resource('cliente','ClienteController');
Route::resource('contacto','ContactoController');
Route::resource('proveedor','ProveedorController');
Route::resource('identificacion','IdentificacionController');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
//FORMA 1 FUNCIONA
Route::get('cliente/{cliente}/contacto','ContactoController@index');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController AdicionarClienteContacto
Route::get('contacto/{cliente}/contacto','ContactoController@AdicionarClienteContacto');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
Route::get('proveedor/{proveedor}/contacto','ContactoController@index');

app/Moneda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Moneda extends Model
{
    //
    protected $table = 'moneda';
    protected $fillable=['mon_codigo, mon_descripcion'];
    public $timestamps = false;
    protected $primaryKey = 'mon_id';
}

app/Http/Controllers/MonedaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Moneda;
use Illuminate\Support\Facades\Redirect;
use DB;

class MonedaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if($request){
            $sql=trim($request->get('buscarTexto'));
            $moneda=DB::table('moneda')->where('mon_descripcion','LIKE','%'.$sql.'%')
            ->orderBy('mon_id','desc')
            ->paginate(10);
        return view('moneda.index',["moneda"=>$moneda,"buscarTexto"=>$sql]);
        //return $moneda;
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $moneda= new Moneda();
        $moneda->mon_codigo= $request->codigo;
        $moneda->mon_descripcion= $request->descripcion;
        //return $moneda;
        $moneda->save();
        return Redirect::to("moneda");


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $moneda= Moneda::findOrFail($request->mon_id);
        $moneda->mon_codigo= $request->codigo;
        $moneda->mon_descripcion= $request->descripcion;
        $moneda->save();
        return Redirect::to("moneda");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
}

resources/views/moneda/form.blade.php
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Codigo</label>
    <div class="col-md-9">
        <input type="text" name="codigo" id="mon_codigo" class="form-control" placeholder="Codigo de Moneda"require pattern="[a-zA-Z]{0,30}">
    </div>
</div>

<div class="form-group row">
    <label class="col-md-3 form-control-label" for="descripcion">Descripcion</label>
    <div class="col-md-9">
    <input type="text" name="descripcion" id="mon_descripcion" class="form-control" placeholder="Ingrese tipo de moneda">
    </div>
</div>



<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-2x"></i> Cerrar</button>
  <button type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i> Guardar</button>
                           
</div>

resources/views/moneda/index.blade.php
@extends('principal')
@section('contenido')
      <div class="content-wrapper">
        
        <!-- Main content -->
        <section class="content">
          
          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">E-Cargo Overseas Group</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
	                  	<div class="col-md-12">
		                          <!--Contenido-->
                                  <div class="container-fluid">
                <!-- Ejemplo de tabla Listado -->
                <div class="card">
                    <div class="card-header">

                       <h2>Listado de Monedas</h2><br/>
                      
                        <button class="btn btn-primary btn-lg" type="button" data-toggle="modal" data-target="#abrirmodal">
                            <i class="fa fa-plus fa-2x"></i>&nbsp;&nbsp;Agregar Moneda
                        </button>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-6">
                            {!!Form::open(array('url'=>'moneda','method'=>'GET','autocomplete'=>'on','role'=>'search'))!!} 
                                <div class="input-group">
                        
                                    <input type="text" name="buscarTexto"class="form-control" placeholder="Buscar texto" value="{{$buscarTexto}}">
                                    <button type="submit"  class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
                                </div>
                                {{Form::close()}}
                                <table class="table table-bordered table-striped table-sm">
                                    <thead>
                                     <tr class="bg-primary">
                                   
                                        <th>Codigo</th>
                                        <th>Descripcion</th>
                                        <th>Editar</th>
                                     </tr>
                                    </thead>
                             <tbody>
                               @foreach($moneda as $mo)
                                <tr>
                                    
                                    <td>{{$mo->mon_codigo}}</td>
                                    <td>{{$mo->mon_descripcion}}</td>
                                    <td>
                                        <button type="button" class="btn btn-info btn-md" data-mon_id="{{$mo->mon_id}}" data-codigo="{{$mo->mon_codigo}}" data-descripcion="{{$mo->mon_descripcion}}" data-toggle="modal" data-target="#abrirmodalEditarMon">

                                          <i class="fa fa-edit fa-2x"></i> Editar
                                        </button> &nbsp;
                                    </td>
                                </tr>
                              @endforeach
                            </tbody>
                        </table>
                        <div class="modal fade" id="abrirmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Agregar Moneda</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                            
                            
                             

                            <form action="{{route('moneda.store')}}" method="post" class="form-horizontal">
                               
                                {{csrf_field()}}
                                @include('moneda.form')

                            </form>

                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
             <!-- empieza EDITAR Moneda -->
            <div class="modal fade" id="abrirmodalEditarMon" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Actualizar Moneda</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                             

                            <form action="{{route('moneda.update','test')}}" method="post" class="form-horizontal">
                                
                                {{method_field('patch')}}
                                {{csrf_field()}}

                                <input type="hidden" id="mon_id" name="mon_id" value="">
                                
                                @include('moneda.form')

                            </form>
                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!--Fin del modal-->

                        
                            </div>
                        </div>
          <!--Fin Contenido-->
                           </div>
                        </div>
		                    
                  		</div>
                  	</div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@endsection