routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('principal');
});
Route::resource('pais','PaisController');
Route::resource('empresa','EmpresaController');
Route::resource('sucursal','SucursalController');
Route::resource('condicion','CondicionController');
Route::resource('moneda','MonedaController');
Route::resource('contenedor','ContenedorController');  
Route::resource('destino','DestinoController');
Route::resource('emision','EmisionController');
Route::resource('ciudad','CiudadController');
Route::resource('cliente','ClienteController');
Route::resource('contacto','ContactoController');
Route::resource('proveedor','ProveedorController');
Route::resource('identificacion','IdentificacionController');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
//FORMA 1 FUNCIONA
Route::get('cliente/{cliente}/contacto','ContactoController@index');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController AdicionarClienteContacto
Route::get('contacto/{cliente}/contacto','ContactoController@AdicionarClienteContacto');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
Route::get('proveedor/{proveedor}/contacto','ContactoController@index');

app/Sucursal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sucursal extends Model
{
    //
    protected $table='sucursal';
    protected $fillable=['suc_ciudad','suc_estado'];
    public $timestamps=false;
    protected $primaryKey='suc_id';
}

app/Http/Controllers/SucursalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use App\Sucursal;
use App\EmpresaSucursal;
use App\Direccion;
use DB;


class SucursalController extends Controller
{
    //
    public function index(Request $request)
    {
        //
        if($request){ 

            $sql=trim($request->get('buscarTexto'));
              $sucursal=DB::table('sucursal as S')
              ->join('empresa_sucursal as ES','S.suc_id','=','ES.suc_id')
              ->join('empresa as E','E.emp_id','=','ES.emp_id')
              ->join('direccion as D', 'D.suc_id','=','S.suc_id')
              ->select('S.suc_id','S.suc_ciudad','E.emp_nombre as empresa','D.dir_descripcion as descripcion')     
              ->where('S.suc_ciudad','LIKE','%'.$sql.'%')
              ->orwhere('E.emp_nombre','LIKE','%'.$sql.'%')
              ->orderBy('S.suc_ciudad','asc')
              ->paginate(6);

            $empresa=DB::table('empresa')
            ->select('emp_id','emp_nombre')
            ->get();

            $empresa_sucursal=DB::table('empresa_sucursal')
            ->select('emp_id','suc_id')
            ->get();

            $direccion = DB::table('direccion')
            ->select ('dir_id','dir_descripcion')
            ->get();

            return view('sucursal.index',["sucursal"=>$sucursal,"empresa"=>$empresa,"buscarTexto"=>$sql]);                
        }
    }

    public function store(Request $request)
    {
        $sucursal = new Sucursal();
        $sucursal->suc_ciudad=$request->ciudad;
        $sucursal->suc_estado= $request->estado;        
        //$sucursal->save();

        $sucursalempresa = new EmpresaSucursal();
        //$sucursalempresa->emp_id=$request->emp_id;
        //$sucursalempresa->suc_id= $request->suc_id;        
        //$sucursalempresa->save();

        $direccion = new Direccion();
        //$direccion 

        ['dir_descripcion','suc_id','em_id','em_id','prov_id','cli_id','nav_id'];


        return Redirect::to("sucursal");
    }

    public function update(Request $request)
    {
        $ciudad= Ciudad::findOrFail($request->ciu_id);
        $ciudad->ciu_codigo=$request->codigo;
        $ciudad->ciu_descripcion= $request->descripcion;
        $ciudad->pais_id;
        $ciudad->save();
        return Redirect::to("ciudad");
    }

    public function destroy(Request $request)
    {
        $empresa = Empresa::findOrFail($request->emp_id);
        $empresa->destroy($request->emp_id);        
        return Redirect::to("empresa");    	
    }
}

resources/views/sucursal/form.blade.php
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="text-input">Ciudad</label>
    <div class="col-md-9">
        <input type="text" name="ciudad" id="suc_ciudad" class="form-control" placeholder="Ciudad"require pattern="[a-zA-Z]{0,30}">
    </div>
</div>

<!--PARA JALAR DATOS DE EMPRESA-->
<div class="form-group row">
<label class="col-md-3 form-control-label" for="titulo">Empresa</label>
            
    <div class="col-md-9">
           
        <select class="form-control" name="emp_id" id="emp_id" required="">
                                                
        <option value="0" disabled>Seleccione Empresa</option>
        @foreach($empresa as $emp)
        <option value="{{$emp->emp_id}}">{{$emp->emp_nombre}}</option>      
        @endforeach

        </select>
            
    </div>
</div>

@include('direccion.form')

<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-2x"></i> Cerrar</button>
  <button type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i> Guardar</button>
                           
</div>

resources/views/sucursal/index.blade.php
@extends('principal')
@section('contenido')
<div class="content-wrapper">
        
        <!-- Main content -->
        <section class="content">
          
          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">E-Cargo Overseas Group</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
	                  	<div class="col-md-12">
		                          <!--Contenido-->
                                  <div class="container-fluid">
                <!-- Ejemplo de tabla Listado -->
                <div class="card">
                    <div class="card-header">

                       <h2>Listado de Sucursales</h2><br/>
                      
                        <button class="btn btn-primary btn-lg" type="button" data-toggle="modal" data-target="#abrirmodal">
                            <i class="fa fa-plus fa-2x"></i>&nbsp;&nbsp;Agregar Sucursal
                        </button>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-6">
							<!-- PARA BUSCADOR INICIO-->
                            {!!Form::open(array('url'=>'sucursal','method'=>'GET','autocomplete'=>'on','role'=>'search'))!!} 
                                <div class="input-group">
                        
                                    <input type="text" name="buscarTexto"class="form-control" placeholder="Buscar texto" value="{{$buscarTexto}}">
                                    <span class="input-group-btn">
                                    <button type="submit"  class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button></span>
                                </div>
                                {{Form::close()}}
							<!-- PARA BUSCADOR FIN-->
                                <table class="table table-bordered table-striped table-sm">
                                    <thead>
                                     <tr class="bg-primary">
                                   
                                        <th>Empresa</th>
                                        <th>Ciudad</th>
                                        <th>Dirección</th>
                                        <!--<th>Zona</th>
                                        <th>Avenida</th>
                                        <th>Estado</th>
                                        <th>Calle</th>
                                        <th>Número</th>
                                        <th>Edificio</th>
                                        <th>Piso</th>
                                        <th>Número Oficina</th>-->

                                     </tr>
                                    </thead>
                             <tbody>
                               @foreach($sucursal as $suc)
                                <tr>                                    
                                    <td>{{$suc->suc_ciudad}}</td>
                                    <td>{{$suc->empresa}}</td>                  
                                    <td>{{$suc->descripcion}}</td>                               
                                    <td>
                                        <button type="button" class="btn btn-info btn-md" data-suc_id="{{$suc->suc_id}}" data-suc_ciudad="{{$suc->suc_ciudad}}" data-toggle="modal" data-target="#abrirmodalEditar">
                                          <i class="fa fa-edit fa-2x"></i>Editar
                                        </button> &nbsp;
                                    <td>
                                        <button type="button" class="btn btn-danger btn-md" data-emp_id="{{$suc->suc_id}}" data-toggle="modal" data-target="#abrirmodalEliminar"> 
                                          <i class="fa fa-edit fa-2x"></i>Eliminar
                                        </button> &nbsp;
                                    </td>
                                    </td>
                                </tr>
                              @endforeach
                            </tbody>
                        </table>
                        <!-- PARA PAGINACION INICIO-->                        
                         {{$sucursal->appends(['buscarTexto' => $buscarTexto])->links()}}
                        <!-- PARA PAGINACION FIN-->
                        <!-- INICIO DEL MODAL AGRAGAR-->
                        <div class="modal fade" id="abrirmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                			<div class="modal-dialog modal-primary modal-lg" role="document">
                    			<div class="modal-content">
                        		<div class="modal-header">
                            <h4 class="modal-title">Agregar Sucursal</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">     
                            <form action="{{route('sucursal.store')}}" method="post" class="form-horizontal">                            
                                {{csrf_field()}}
                                @include('sucursal.form')                             

                            </form>
                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
             <!-- INICIO MODAL ACTUALIZAR -->
            <div class="modal fade" id="abrirmodalEditar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Actualizar Sucursal</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                             

                            <form action="{{route('sucursal.update','test')}}" method="post" class="form-horizontal">
                                
                                {{method_field('patch')}}
                                {{csrf_field()}}

                                <input type="hidden" id="suc_id" name="suc_id" value="">
                                
                                @include('sucursal.form')

                            </form>
                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!--Fin del modal ELIMINAR-->
             <div class="modal fade" id="abrirmodalEliminar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Eliminar Sucursal</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                             

                            <form action="{{route('sucursal.destroy','test')}}" method="post" class="form-horizontal">
                                
                                {{method_field('delete')}}
                                {{csrf_field()}}
                                <!--CAMPO OCULTO PARA MANEJAR EL ID DE EMPRESA-->
                                <input type="hidden" id="suc_id" name="suc_id" value="">      
                                <p>Está seguro que desea Eliminar la Sucursal?</p>
                                <div class="modal-footer">
                                	<button type="button" class="btn btn-danger" data-dismiss="modal"><i class = "fa fa-times fa-2x"></i>Cerrar</button>
                                	<button type="submit" class="btn btn-success" ><i class = "fa fa-lock fa-2x"></i>Aceptar</button>
                                	
                                </div>
                                </form>
                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!--Fin del modal ELIMINAR-->

                        
                            </div>
                        </div>
          <!--Fin Contenido-->
                           </div>
                        </div>
		                    
                  		</div>
                  	</div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->	
@endsection