routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('principal');
});
Route::resource('pais','PaisController');
Route::resource('empresa','EmpresaController');
Route::resource('sucursal','SucursalController');
Route::resource('condicion','CondicionController');
Route::resource('moneda','MonedaController');
Route::resource('contenedor','ContenedorController');  
Route::resource('destino','DestinoController');
Route::resource('emision','EmisionController');
Route::resource('ciudad','CiudadController');
Route::resource('cliente','ClienteController');
Route::resource('contacto','ContactoController');
Route::resource('proveedor','ProveedorController');
Route::resource('identificacion','IdentificacionController');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
//FORMA 1 FUNCIONA
Route::get('cliente/{cliente}/contacto','ContactoController@index');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController AdicionarClienteContacto
Route::get('contacto/{cliente}/contacto','ContactoController@AdicionarClienteContacto');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
Route::get('proveedor/{proveedor}/contacto','ContactoController@index');

app/Destino.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Destino extends Model
{
    //
    protected $table = 'destino';
    protected $fillable=['dest_descripcion'];
    public $timestamps=false;
    protected $primaryKey='dest_id';
}

app/Http/Controllers/DestinoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Destino;
use Illuminate\Support\Facades\Redirect;
use DB;

class DestinoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if($request){
            $sql=trim($request->get('buscarTexto'));
            $destino=DB::table('destino')->where('dest_descripcion','LIKE','%'.$sql.'%')
            ->orderBy('dest_id','desc')
            ->paginate(10);
        return view('destino.index',["destino"=>$destino,"buscarTexto"=>$sql]);
        //return $destino;
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $destino= new Destino();
        $destino->dest_descripcion= $request->descripcion;
        $destino->save();
        return Redirect::to("destino");


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //
        $destino= Destino::findOrFail($request->dest_id);
        $destino->dest_descripcion= $request->descripcion;
        $destino->save();
        return Redirect::to("destino");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
}

resources/views/destino/form.blade.php
<div class="form-group row">
    <label class="col-md-3 form-control-label" for="descripcion">Descripcion</label>
    <div class="col-md-9">
    <input type="text" name="descripcion" id="dest_descripcion" class="form-control" placeholder="Ingrese descripcion">
    </div>
</div>



<div class="modal-footer">
  <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-2x"></i> Cerrar</button>
  <button type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i> Guardar</button>
                           
</div>

resources/views/destino/index.blade.php
@extends('principal')
@section('contenido')
      <div class="content-wrapper">
        
        <!-- Main content -->
        <section class="content">
          
          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">E-Cargo Overseas Group</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
	                  	<div class="col-md-12">
		                          <!--Contenido-->
                                  <div class="container-fluid">
                <!-- Ejemplo de tabla Listado -->
                <div class="card">
                    <div class="card-header">

                       <h2>Destino</h2><br/>
                      
                        <button class="btn btn-primary btn-lg" type="button" data-toggle="modal" data-target="#abrirmodal">
                            <i class="fa fa-plus fa-2x"></i>&nbsp;&nbsp;Agregar Destino
                        </button>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-6">
                            {!!Form::open(array('url'=>'destino','method'=>'GET','autocomplete'=>'on','role'=>'search'))!!} 
                                <div class="input-group">
                        
                                    <input type="text" name="buscarTexto"class="form-control" placeholder="Buscar texto" value="{{$buscarTexto}}">
                                    <button type="submit"  class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
                                </div>
                                {{Form::close()}}
                                <table class="table table-bordered table-striped table-sm">
                                    <thead>
                                     <tr class="bg-primary">
                                   
                                        <th>Id</th>
                                        <th>Descripcion</th>
                                        <th>Editar</th>
                                     </tr>
                                    </thead>
                             <tbody>
                               @foreach($destino as $dest)
                                <tr>
                                    
                                    <td>{{$dest->dest_id}}</td>
                                    <td>{{$dest->dest_descripcion}}</td>
                                    <td>
                                        <button type="button" class="btn btn-info btn-md" data-dest_id="{{$dest->dest_id}}" data-descripcion="{{$dest->dest_descripcion}}" data-toggle="modal" data-target="#abrirmodalEditarDest">

                                          <i class="fa fa-edit fa-2x"></i> Editar
                                        </button> &nbsp;
                                    </td>
                                </tr>
                              @endforeach
                            </tbody>
                        </table>
                        <div class="modal fade" id="abrirmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Agregar Destino</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                            
                            
                             

                            <form action="{{route('destino.store')}}" method="post" class="form-horizontal">
                               
                                {{csrf_field()}}
                                @include('destino.form')

                            </form>

                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
             <!-- empieza EDITAR Moneda -->
            <div class="modal fade" id="abrirmodalEditarDest" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                <div class="modal-dialog modal-primary modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Actualizar destino</h4>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                        </div>
                       
                        <div class="modal-body">
                             

                            <form action="{{route('destino.update','test')}}" method="post" class="form-horizontal">
                                
                                {{method_field('patch')}}
                                {{csrf_field()}}

                                <input type="hidden" id="dest_id" name="dest_id" value="">
                                
                                @include('destino.form')

                            </form>
                        </div>
                        
                    </div>
                    <!-- /.modal-content -->
                </div>
                <!-- /.modal-dialog -->
            </div>
            <!--Fin del modal-->

                        
                            </div>
                        </div>
          <!--Fin Contenido-->
                           </div>
                        </div>
		                    
                  		</div>
                  	</div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
@endsection