routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('principal');
});
Route::resource('pais','PaisController');
Route::resource('empresa','EmpresaController');
Route::resource('sucursal','SucursalController');
Route::resource('condicion','CondicionController');
Route::resource('moneda','MonedaController');
Route::resource('contenedor','ContenedorController');  
Route::resource('destino','DestinoController');
Route::resource('emision','EmisionController');
Route::resource('ciudad','CiudadController');
Route::resource('cliente','ClienteController');
Route::resource('contacto','ContactoController');
Route::resource('proveedor','ProveedorController');
Route::resource('identificacion','IdentificacionController');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
//FORMA 1 FUNCIONA
Route::get('cliente/{cliente}/contacto','ContactoController@index');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController AdicionarClienteContacto
Route::get('contacto/{cliente}/contacto','ContactoController@AdicionarClienteContacto');

//PARA ENVIAR LA ID DE CLIENTE AL CONTROLADOR ContactoController
Route::get('proveedor/{proveedor}/contacto','ContactoController@index');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'cliente';
    protected $fillable = ['cli_nombreEmpresa','cli_nombresPersona','cli_apellidosPersona','cli_tipo_doc','cli_num_doc','cli_ci'];
    public $timestamps = false;
    protected $primaryKey = 'cli_id';
	
	public function telefonos()
	{
	    return $this->hasMany(Telefono::class,'cli_id');
	}

	public function direcciones()
	{
	    return $this->hasMany(Direccion::class,'cli_id');
	}

	public function correos()
	{
	    return $this->hasMany(Correo::class,'cli_id');
	}

	public function contactos()
	{
	    return $this->hasMany(Contacto::class,'cli_id');
	}
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Cliente;
use App\Contacto;
use App\Telefono;
use App\Direccion;
use App\Correo;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use DB;

class ClienteController extends Controller
{    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */    
    public function index(Request $request)
    {        
        if($request){
            $sql=trim($request -> get('buscarTexto'));
            $cliente = Cliente::where ('cli_nombre','LIKE','%'.$sql.'%')            
            ->orderBy ('cli_nombre','asc')
            ->with(['telefonos','direcciones','correos'])
            ->paginate (10);

            $ciudad=DB::table('ciudad')
            // ->select('ciu_id','ciu_codigo','ciu_descripcion','pais_id')
            ->select('ciu_descripcion','pais_id')
            /*CAMBIAR EL WHERE DEACUERDO A LA BASE DE DATOS Y EL CODIGO PARA BOLIVIA Y CHILE*/
            /*PARA BOLIVIA*/
            ->where('pais_id','=','1')
            /*PARA CHILE*/
            /*->orwhere('pais_id','=','2')*/
            ->get();            
            return view('cliente.index',["cliente"=>$cliente,"ciudad"=>$ciudad,"buscarTexto"=>$sql]);
        }
    }

    public function retornaCiudadAjax(Request $request)
    {        
        $ciudad_ajax=DB::table('ciudad')
        ->select('ciu_descripcion')
        //RECIBIMOS LOS ID DE AJAX
        ->where('pais_id','=',$request->id_bolivia)
        ->orwhere('pais_id','=',$request->id_chile)
        ->get();
        return response()->json([
            'ciudades'=>$ciudad_ajax
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cliente = new Cliente();
        $cliente->cli_nombre = $request->nombre;
        //SELECT TIPO DOCUMENTO SE MANEJA DE LA MISMA FORMA QUE LOS DEMAS CAMPOS
        $cliente->cli_tipo_doc = $request->tipo_doc;      
        $cliente->cli_num_doc = $request->num_doc;
        $cliente->cli_ci = $request->ci;
        $cliente->cli_tipo = $request->cli_tipo;
        $cliente->save();        

        $x = 0;
        if($request->direcciones != null){
            foreach ($request->direcciones as $dir)
            {   
                $direccion = new Direccion();
                $direccion->dir_descripcion = $dir;
                $direccion->dir_ciudad = $request->ciudades[$x];
                $x++;
                $direccion->cli_id = $cliente->cli_id;
                $direccion->save();
            }
        }
        else{
            $mensaje = "ERROR EN LA DIRECCIÓN... NO SE GUARDO CORRECTAMENTE";
        }
        if($request->correos != null){
            foreach ($request->correos as $co)
            {   
                $correo = new Correo();
                $correo->correo_descripcion = $co;
                $correo->correo_estado = 1;
                $correo->cli_id = $cliente->cli_id;
                $correo->save();
            }
        }
        else{
            $mensaje = "ERROR EN EL CORREO... NO SE GUARDO CORRECTAMENTE";
        }
        /*PARA TELEFONO*/
        $x = 0;
        if($request->telefonos != null){
            foreach ($request->telefonos as $tel)
            {   
                $telefono = new Telefono();
                $telefono->telefono_numero = $tel;
                $telefono->telefono_tipo = $request->telefono_tipo[$x];
                $x++;
                $telefono->cli_id = $cliente->cli_id;
                $telefono->save();
            }
        }
        else{
            $mensaje = "ERROR EN EL TELÉFONO... NO SE GUARDO CORRECTAMENTE";
        }
        return Redirect::to("cliente");        
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function show(Cliente $cliente)
    {
        //
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $cliente = Cliente::findOrFail($request->cli_id);
        $cliente->cli_nombre = $request->nombre;
        $cliente->cli_tipo_doc = $request->tipo_doc;
        $cliente->cli_num_doc = $request->num_doc;
        $cliente->cli_ci = $request->ci;
        $cliente->save();

        $x = 0;
        $cliente->direcciones()->delete();
        if($request->direcciones != null){
            foreach ($request->direcciones as $dir)
            {   
                $direccion = new Direccion();
                $direccion->dir_descripcion = $dir;
                $direccion->dir_ciudad = $request->ciudades[$x];
                $x++;
                $direccion->cli_id = $cliente->cli_id;
                $direccion->save();
            }
        }
        else{
            $mensaje = "DEBE AÑADIR UNA DIRECCION";
        }
        $cliente->correos()->delete();
        if($request->correos != null){            
            foreach ($request->correos as $co)
            {   
                $correo = new Correo();
                $correo->correo_descripcion = $co;
                $correo->correo_estado = 1;
                $correo->cli_id = $cliente->cli_id;
                $correo->save();
            }
        }
        else{
            $mensaje = "DEBE AÑADIR UN CORREO";
        }
        /*PARA TELEFONO*/
        $x = 0;
        $cliente->telefonos()->delete();
        if($request->telefonos != null){            
            $x = 0;
            foreach ($request->telefonos as $tel)
            {   
                $telefono = new Telefono();
                $telefono->telefono_numero = $tel;
                $telefono->telefono_tipo = $request->telefono_tipo[$x];
                $x++;
                $telefono->cli_id = $cliente->cli_id;
                $telefono->save();
            }
        }
        else{
            $mensaje = "DEBE AÑADIR UN TELEFONO";
        }        
        return Redirect::to("cliente");
        // return view("cliente")->with('mensaje',$mensaje);
        // return $mensaje;
        // return redirect()->action('ClienteController@index', $mensajes);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cliente  $cliente
     * @return \Illuminate\Http\Response
     */    

    public function destroy(Request $request)
    {
        $cliente = Cliente::findOrFail($request->cli_id);
        // $x = $cliente->contactos()->get();
        foreach ($cliente->contactos()->get() as $cont){
            $contacto = Contacto::findOrFail($cont->cont_id);
            $contacto->telefonos()->delete();
            $contacto->correos()->delete();
            $contacto->direcciones()->delete();
            $contacto->delete();
        }
        $cliente->telefonos()->delete();
        $cliente->correos()->delete();
        $cliente->direcciones()->delete();
        $cliente->delete();
        return Redirect::to("cliente");
    }

}

resources/views/cliente/form.blade.php
<div class="form-group row cli_tipo" id="tipoCliente" style="display: none;">
    <label class="col-md-3 form-control-label" for="cli_tipo">Tipo de Cliente a Registrar</label>
    <div class="col-md-3">        
        <select name="cli_tipo" id="cli_tipo" class="form-control" onchange="mostrarCampos()">
            <option value="" selected disabled>--Seleccione--</option>
            <option value="empresa">Empresa</option>
            <option value="persona">Persona Natural</option>
        </select>
    </div>
</div>

<div class="form-group row" id="nombreCliente">    
    <label class="col-md-3 form-control-label" for="cli_nombre">Nombre</label>    
    <div class="col-md-8">        
        <input type="text" name="nombre" id="cli_nombre" class="form-control" placeholder="Nombre del Cliente">
    </div>
</div>

<div class="form-group row carnetCliente" id="carnetCliente">
    <label class="col-md-3 form-control-label" for="cli_ci">Carnet de Identidad</label>
    <div class="col-md-3">
        <input type="text" name="ci" id="cli_ci" class="form-control" placeholder="Carnet de Identidad">
    </div>
</div>

<div class="form-group row" id="tipoDocumentoCliente">
    <label class="col-md-3 form-control-label" for="cli_tipo_doc">Tipo Documento</label>
    <div class="col-md-2">        
        <select name="tipo_doc" id="cli_tipo_doc" class="form-control">
            <option value="" selected disabled="">--Seleccione--</option>            
            <option value="NIT">Nit</option>
            <option value="RUC">Ruc</option>
            <option value="Ninguno">Ninguno</option>
        </select>
    </div>
</div>

<div class="form-group row" id="numeroDocumentoCliente">
    <label class="col-md-3 form-control-label" for="cli_num_doc">Número Documento</label>
    <div class="col-md-3">
        <input type="text" name="num_doc" id="cli_num_doc" class="form-control" placeholder="Número de Documento">
    </div>
</div>

<div class="form-group row" id="direccionCliente">
    <label class="col-md-3 form-control-label">Dirección(es)</label>
    <div class="col-md-9">        
        <table id="tablaDireccion" class= "tabla_wrapperDireccion">
            <tr> 
                <td>
                    <!-- PARA QUE ESTEN ALINEADOS LOS CAMPOS DE SELECT PARA DIRECCION Y CIUDAD -->
                </td>                           
                <td>
                    <label class="form-control-label"></label>
                </td>                
                <td>
                    <a href="#" class="add_buttonDireccion" title="Añadir Dirección"><button id="adicionar" type="button" class="btn btn-success" onclick="masDirecciones()" style="margin-left: 15px; width: 70px;">Mas +</button></a>                   
                </td>
            </tr>            
        </table>        
    </div>
</div>

<div class="form-group row" id="telefonoCliente">
    <label class="col-md-3 form-control-label">Teléfono(s)</label>
    <div class="col-md-4">        
        <table id="tablaTelefono" class= "tabla_wrapperTelefono">
            <tr>
                <td>
                    <!-- PARA QUE ESTEN ALINEADOS LOS CAMPOS DE SELECT PARA TIPO DE TELEFONO Y NUMERO DE TELEFONO -->
                </td>                            
                <td>
                    <label class="form-control-label" style="width:185px;">Número(s)</label>
                </td>                
                <td>
                    <a href="#" class="add_buttonTelefono" title="Add field"><button id="adicionar" type="button" class="btn btn-success" onclick="masTelefonos()" style="margin-left: 15px; width: 70px;">Mas +</button></a>                    
                </td>
            </tr>            
        </table>        
    </div>
</div>

<div class="form-group row" id="correoCliente">
    <label class="col-md-3 form-control-label">Correo(s)</label>
    <div class="col-md-9">        
        <table id="tablaCorreo" class= "tabla_wrapperCorreo">
            <tr>                            
                <td>
                    <label class="form-control-label"></label>
                </td>                
                <td>
                    <a href="#" class="add_buttonCorreo" title="Add field"><button id="adicionar" type="button" class="btn btn-success" onclick="masCorreos()" style="margin-left: 15px; width: 70px;">Mas +</button></a>                    
                </td>
            </tr>            
        </table>        
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-times fa-2x"></i> Cerrar</button>
    <button id="btnguardar" type="submit" class="btn btn-success"><i class="fa fa-save fa-2x"></i>Guardar</button> 
</div>

resources/views/cliente/index.blade.php
@extends('principal')
@section('contenido')
<div class="content-wrapper">        
        <!-- Main content -->
    <section class="content">          
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">E-Cargo Overseas Group</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
                        <div class="col-md-12">
		                          <!--Contenido-->
                            <div class="container-fluid">
                <!-- Ejemplo de tabla Listado -->
                <div class="card">
                    
                    <div class="card-header">
                       <h2>Listado de Clientes</h2><br/>                       
                        <button class="btn btn-primary btn-lg" type="button" data-toggle="modal" data-target="#abrirmodalCliente" onclick="cargarCiudades(); ocultarCampos();">
                            <i class="fa fa-plus fa"></i>&nbsp;&nbsp;Agregar Cliente
                        </button>
                    </div>
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-12">
							<!--BUSCADOR INICIO-->
                            {!!Form::open(array('url'=>'cliente','method'=>'GET','autocomplete'=>'on','role'=>'search'))!!} 
                                <div class="input-group">                        
                                    <input type="text" name="buscarTexto"class="form-control" placeholder="Buscar texto" value="{{$buscarTexto}}">
                                    <span class="input-group-btn">
                                        <button type="submit"  class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
                                    </span>
                                </div>
                            {{Form::close()}}
							<!--BUSCADOR FIN-->                            
                                <table class="table table-bordered table-striped table-sm" id="tabla">
                                    <thead>
                                        <tr class="bg-primary">
                                            <th>Nombre</th>                                     
                                            <th>Tipo Documento</th>
                                            <th>Número Documento</th>
                                            <th>Identificacion Ciudadano</th>
                                            <th>Dirección</th>                                 
                                            <th>Teléfono</th>
                                            <th>Email</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($cliente as $cli)
                                    <tr>                                    
                                        <td>{{$cli->cli_nombre}}</td>
                                        <td>{{$cli->cli_tipo_doc}}</td>
                                        <td>{{$cli->cli_num_doc}}</td>
                                        <td>{{$cli->cli_ci}}</td>
                                        <td>
                                            <select>
                                                @foreach($cli->direcciones as $dir)
                                                     <option value="{{$dir->dir_descripcion}}" class ="form-control">{{$dir->dir_ciudad}}:&nbsp;{{$dir->dir_descripcion}}</option>
                                                @endforeach
                                            </select>
                                        </td>
                                        <td>
                                            <select>
                                                @foreach($cli->telefonos as $tel)
                                                     <option value="{{$tel->telefono_numero}}" class ="form-control">{{$tel->telefono_tipo}}:&nbsp;{{$tel->telefono_numero}}</option>
                                                @endforeach
                                            </select>
                                        </td>                                        
                                        <td>
                                            <select>
                                                    @foreach($cli->correos()->get() as $cor)
                                                         <option value="{{$cor->correo_descripcion}}" class ="form-control">{{$cor->correo_descripcion}}</option>
                                                    @endforeach
                                            </select>
                                        </td>
                                        <td>
                                            <a class="btn btn-primary" href="{{url('/cliente/'.$cli->cli_id.'/contacto')}}">Contacto</a>
                                        </td>                    
                                        <td>
                                            <button type="button" class="btn btn-info btn-md" data-cli_id="{{$cli->cli_id}}" data-cli_nombre="{{$cli->cli_nombre}}" data-cli_tipo_doc="{{$cli->cli_tipo_doc}}" data-cli_num_doc="{{$cli->cli_num_doc}}" data-cli_ci="{{$cli->cli_ci}}" data-telefonos="{{json_encode($cli->telefonos()->get())}}"
                                            data-direcciones="{{json_encode($cli->direcciones()->get())}}"
                                            data-correos="{{json_encode($cli->correos()->get())}}"
                                            data-ciudades="{{json_encode($ciudad)}}"
                                            data-cli_tipo="{{$cli->cli_tipo}}"
                                            data-toggle="modal" data-target="#abrirmodalEditarCliente"onclick="cargarCiudades();">
                                            <i class="fa fa-edit fa"></i>Editar
                                            </button>&nbsp;                           
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger btn-md" data-cli_id="{{$cli->cli_id}}" data-toggle="modal" data-target="#abrirmodalEliminarCliente"> 
                                            <i class="fa fa-edit fa"></i>Eliminar
                                            </button> &nbsp;
                                        </td>                                        
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>                                
                            <!-- PAGINACION INICIO-->                            
                            {{$cliente->appends(['buscarTexto' => $buscarTexto])->links()}}
                            <!-- PAGINACION FIN-->

                            <!-- INICIO DEL MODAL AGREGAR-->
                            <div class="modal fade" id="abrirmodalCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                    			<div class="modal-dialog modal-primary modal-lg" role="document">
                        			<div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Agregar Cliente</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>                       
                                        <div class="modal-body">
                                            <form id="formularioAgregarCliente" action="{{route('cliente.store')}}" method="post" class="form-horizontal">
                                                {{csrf_field()}}
                                                @include('cliente.form')   
                                            </form>
                                        </div>                        
                                    </div>
                                <!-- /.modal-content -->
                                </div>
                            <!-- /.modal-dialog -->
                            </div>                            
                            <!-- INICIO MODAL ACTUALIZAR -->
                            <div class="modal fade" id="abrirmodalEditarCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                                <div class="modal-dialog modal-primary modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Actualizar Cliente</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>                      
                                <div class="modal-body">
                                    <form id="formularioEditarCliente" action="{{route('cliente.update','test')}}" method="post" class="form-horizontal">  
                                        {{method_field('patch')}}
                                        {{csrf_field()}}
                                        <input type="hidden" id="cli_id" name="cli_id" value="">
                                        @include('cliente.form')
                                    </form>                                
                                </div>
                                    </div>
                                <!-- /.modal-content -->
                                </div>
                            <!-- /.modal-dialog -->
                            </div>
                            <!--FIN MODAL ACTUALIZAR-->
                            <!--INICIO MODAL ELIMINAR-->
                            <div class="modal fade" id="abrirmodalEliminarCliente" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" style="display: none;" aria-hidden="true">
                                <div class="modal-dialog modal-primary modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Eliminar Cliente</h4>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>                                       
                                        <div class="modal-body">
                                            <form action="{{route('cliente.destroy','test')}}" method="post" class="form-horizontal">
                                                {{method_field('delete')}}
                                                {{csrf_field()}}
                                                <!--CAMPO OCULTO PARA MANEJAR EL ID DEL CLIENTE-->
                                                <input type="hidden" id="cli_id" name="cli_id" value="">      
                                                <p>Está seguro que desea Eliminar al Cliente?</p>
                                                <div class="modal-footer">
                                                	<button type="button" class="btn btn-danger" data-dismiss="modal"><i class = "fa fa-times fa-2x"></i>Cerrar</button>
                                                	<button type="submit" class="btn btn-success" ><i class = "fa fa-check fa-2x"></i>Aceptar</button>  	
                                                </div>
                                            </form>
                                        </div>                                        
                                    </div>
                                    <!-- /.modal-content -->
                                </div>
                                <!-- /.modal-dialog -->
                            </div>
                            <!--FIN MODAL ELIMINAR-->
                            </div>
                        </div>
                    <!--Fin Contenido-->
                    </div>
                </div>		                    
                  		    </div></<!--/container-fluid-->
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->	
@endsection